export const CLIENT_SECRET = 'UZOXZCPGYAMJ03UET4PBTB2FMWUUOHBQV5SB5YPCSEB2QMA1';
export const CLIENT_ID = 'QRTOD5LI3P5M3Q2VHZVOXHT5TB3DIYCJD0UKSSLBZIMGSSEA';
export const FSVERSION = '20190425';
export const API_SEARCH_URL = 'https://api.foursquare.com/v2/venues/explore';